# Generated by Django 5.0.14 on 2026-09-16 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20, unique=True)),
                ('poste', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('date_embauche', models.DateField()),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('sexe', models.CharField(blank=True, choices=[('H', 'Homme'), ('F', 'Femme')], max_length=1)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_desactivation', models.DateTimeField(blank=True, null=True)),
                ('cree_par', models.ForeignKey(blank=True, help_text='Administrateur ou Responsable RH ayant cree la fiche (tracabilite, RG-13).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fiches_employes_creees', to=settings.AUTH_USER_MODEL)),
                ('utilisateur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fiche_employe', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Employe',
                'verbose_name_plural': 'Employes',
                'ordering': ['utilisateur__last_name', 'utilisateur__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_document', models.CharField(choices=[('CONTRAT', 'Contrat de travail'), ('CNI', "Piece d'identite (CNI)"), ('DIPLOME', 'Diplome / certificat'), ('CV', 'CV'), ('ATTESTATION', 'Attestation de travail'), ('BULLETIN', 'Bulletin de paie')], max_length=15)),
                ('fichier', models.FileField(upload_to='documents/')),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('ajoute_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents_ajoutes', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='employees.employe')),
            ],
            options={
                'verbose_name': 'Document RH',
                'verbose_name_plural': 'Documents RH',
                'ordering': ['-date_ajout'],
            },
        ),
        migrations.CreateModel(
            name='Contrat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_contrat', models.CharField(choices=[('CDI', 'Contrat a duree indeterminee (CDI)'), ('CDD', 'Contrat a duree determinee (CDD)'), ('STAGE', 'Stage'), ('PRESTATION', 'Contrat de prestation')], max_length=12)),
                ('poste', models.CharField(max_length=100)),
                ('service', models.CharField(max_length=100)),
                ('salaire', models.DecimalField(decimal_places=2, max_digits=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField(blank=True, help_text='Laisser vide pour un CDI.', null=True)),
                ('periode_essai_mois', models.PositiveSmallIntegerField(default=0)),
                ('signe', models.BooleanField(default=False)),
                ('date_signature', models.DateField(blank=True, null=True)),
                ('fichier_contrat', models.FileField(blank=True, null=True, upload_to='contrats/')),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contrats', to='employees.employe')),
            ],
            options={
                'verbose_name': 'Contrat',
                'verbose_name_plural': 'Contrats',
                'ordering': ['-date_debut'],
            },
        ),
        migrations.CreateModel(
            name='Remuneration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salaire_base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('primes', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('date_effective', models.DateField()),
                ('commentaire', models.CharField(blank=True, max_length=255)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remunerations', to='employees.employe')),
            ],
            options={
                'verbose_name': 'Remuneration',
                'verbose_name_plural': 'Remunerations',
                'ordering': ['-date_effective'],
            },
        ),
    ]
