# Generated by Django 5.0.14 on 2026-09-20 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='fichier',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
