# Generated by Django 5.0.14 on 2026-09-21 08:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_document_fichier_nullable'),
    ]

    operations = [
        migrations.AddField(
            model_name='employe',
            name='contact_urgence_nom',
            field=models.CharField(blank=True, max_length=100, verbose_name="Contact d'urgence (nom)"),
        ),
        migrations.AddField(
            model_name='employe',
            name='contact_urgence_telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name="Contact d'urgence (téléphone)"),
        ),
        migrations.AddField(
            model_name='employe',
            name='etablissement',
            field=models.CharField(blank=True, max_length=120, verbose_name='Établissement'),
        ),
        migrations.AddField(
            model_name='employe',
            name='langues',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='employe',
            name='lieu_travail',
            field=models.CharField(blank=True, max_length=100, verbose_name='Lieu de travail'),
        ),
        migrations.AddField(
            model_name='employe',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='equipe', to='employees.employe', verbose_name='Manager'),
        ),
        migrations.AddField(
            model_name='employe',
            name='nationalite',
            field=models.CharField(blank=True, max_length=60, verbose_name='Nationalité'),
        ),
        migrations.AddField(
            model_name='employe',
            name='niveau_etudes',
            field=models.CharField(blank=True, max_length=60, verbose_name="Niveau d'études"),
        ),
        migrations.AddField(
            model_name='employe',
            name='situation_familiale',
            field=models.CharField(blank=True, choices=[('CELIBATAIRE', 'Célibataire'), ('MARIE', 'Marié(e)'), ('DIVORCE', 'Divorcé(e)'), ('VEUF', 'Veuf / veuve')], max_length=12),
        ),
        migrations.AddField(
            model_name='employe',
            name='specialite',
            field=models.CharField(blank=True, max_length=120, verbose_name='Spécialité'),
        ),
        migrations.AlterField(
            model_name='employe',
            name='matricule',
            field=models.CharField(blank=True, help_text='Laisser vide pour générer automatiquement (EMP-001, EMP-002...).', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='employe',
            name='service',
            field=models.CharField(max_length=100, verbose_name='Département'),
        ),
    ]
