# Generated by Django 5.0.14 on 2026-09-27 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0003_employe_contact_urgence_nom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contrat',
            name='type_contrat',
            field=models.CharField(choices=[('CDI', 'Contrat a duree indeterminee (CDI)'), ('CDD', 'Contrat a duree determinee (CDD)'), ('STAGE', 'Stagiaire'), ('PRESTATION', 'Consultant')], max_length=12),
        ),
    ]
