# Generated by Django 5.0.14 on 2026-09-18 02:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('date_evaluation', models.DateField()),
                ('note', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('commentaire', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_creees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='employees.employe')),
            ],
            options={
                'ordering': ['-date_evaluation', '-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('date_formation', models.DateField()),
                ('duree_heures', models.PositiveSmallIntegerField(default=1)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='formations_creees', to=settings.AUTH_USER_MODEL)),
                ('participants', models.ManyToManyField(blank=True, related_name='formations', to='employees.employe')),
            ],
            options={
                'ordering': ['date_formation', 'titre'],
            },
        ),
        migrations.CreateModel(
            name='Offre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poste', models.CharField(max_length=150)),
                ('type_contrat', models.CharField(max_length=30)),
                ('lieu', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('statut', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiee'), ('POURVUE', 'Pourvue'), ('FERMEE', 'Fermee')], default='BROUILLON', max_length=12)),
                ('date_publication', models.DateField(blank=True, null=True)),
                ('date_limite', models.DateField(blank=True, null=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('creee_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_creees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Candidature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_candidat', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('cv', models.FileField(blank=True, upload_to='candidatures/')),
                ('statut', models.CharField(choices=[('RECUE', 'Recue'), ('EN_REVUE', 'En revue'), ('ENTRETIEN', 'Entretien'), ('RETENUE', 'Retenue'), ('REJETEE', 'Rejetee')], default='RECUE', max_length=12)),
                ('commentaire', models.TextField(blank=True)),
                ('date_candidature', models.DateTimeField(auto_now_add=True)),
                ('offre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatures', to='core.offre')),
            ],
            options={
                'ordering': ['-date_candidature'],
            },
        ),
    ]
