# Generated by Django 5.0.14 on 2026-09-20 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evaluations_criteres_formations_participations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True, verbose_name="Date d'entretien"),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_recrutement',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidature',
            name='recrute',
            field=models.BooleanField(default=False, verbose_name='Candidat recruté'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='saisie_par',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidatures_saisies', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offre',
            name='departement',
            field=models.CharField(blank=True, max_length=100, verbose_name='Département / service'),
        ),
        migrations.AddField(
            model_name='offre',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offres_suivies', to=settings.AUTH_USER_MODEL, verbose_name='Responsable du recrutement'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('RECUE', 'Reçue'), ('EN_REVUE', 'En revue'), ('ENTRETIEN', 'Entretien'), ('RETENUE', 'Retenue'), ('REJETEE', 'Rejetée')], default='RECUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='offre',
            name='statut',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('PUBLIEE', 'Publiée'), ('POURVUE', 'Pourvue'), ('FERMEE', 'Fermée')], default='BROUILLON', max_length=12),
        ),
    ]
