# Generated by Django 5.0.14 on 2026-09-21 08:14

from django.db import migrations, models


def fusionner_en_revue_dans_a_analyser(apps, schema_editor):
    """Le statut « En revue » disparait : ces candidatures redeviennent « A analyser »."""
    Candidature = apps.get_model("core", "Candidature")
    Candidature.objects.filter(statut="EN_REVUE").update(statut="RECUE")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_recrutement_offres_candidatures'),
    ]

    operations = [
        migrations.RunPython(fusionner_en_revue_dans_a_analyser, migrations.RunPython.noop),
        migrations.AddField(
            model_name='candidature',
            name='competences',
            field=models.TextField(blank=True, help_text='Séparées par des virgules.', verbose_name='Compétences clés'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='date_entretien_technique',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entretien technique'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='disponibilite',
            field=models.CharField(blank=True, max_length=100, verbose_name='Disponibilité'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='experience_annees',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Expérience (années)'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='lettre_motivation',
            field=models.FileField(blank=True, upload_to='candidatures/', verbose_name='Lettre de motivation'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='linkedin',
            field=models.URLField(blank=True, verbose_name='Profil LinkedIn'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='localisation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='candidature',
            name='salaire_souhaite',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Salaire souhaité (FCFA / mois)'),
        ),
        migrations.AddField(
            model_name='formation',
            name='annulee',
            field=models.BooleanField(default=False, verbose_name='Formation annulée'),
        ),
        migrations.AddField(
            model_name='formation',
            name='date_fin',
            field=models.DateField(blank=True, null=True, verbose_name='Date de fin'),
        ),
        migrations.AddField(
            model_name='formation',
            name='formateur',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='formation',
            name='heure_debut',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de début'),
        ),
        migrations.AddField(
            model_name='formation',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True, verbose_name='Heure de fin'),
        ),
        migrations.AddField(
            model_name='formation',
            name='lieu',
            field=models.CharField(blank=True, max_length=150, verbose_name='Lieu / salle'),
        ),
        migrations.AddField(
            model_name='offre',
            name='competences',
            field=models.TextField(blank=True, help_text='Séparées par des virgules.', verbose_name='Compétences recherchées'),
        ),
        migrations.AddField(
            model_name='offre',
            name='missions',
            field=models.TextField(blank=True, help_text='Une mission par ligne.', verbose_name='Missions principales'),
        ),
        migrations.AddField(
            model_name='offre',
            name='mode_travail',
            field=models.CharField(blank=True, choices=[('SUR_SITE', 'Sur site'), ('HYBRIDE', 'Hybride'), ('TELETRAVAIL', 'Télétravail')], max_length=12, verbose_name='Lieu de travail'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='cv',
            field=models.FileField(blank=True, upload_to='candidatures/', verbose_name='CV'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='date_entretien',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entretien RH'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='nom_candidat',
            field=models.CharField(max_length=150, verbose_name='Nom complet'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='statut',
            field=models.CharField(choices=[('RECUE', 'À analyser'), ('ENTRETIEN', 'Entretien'), ('RETENUE', 'Retenue'), ('REJETEE', 'Refusée')], default='RECUE', max_length=12),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='telephone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Téléphone'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='date_formation',
            field=models.DateField(verbose_name='Date de début'),
        ),
        migrations.AlterField(
            model_name='formation',
            name='duree_heures',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Durée (heures)'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='date_limite',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'expiration"),
        ),
        migrations.AlterField(
            model_name='offre',
            name='description',
            field=models.TextField(verbose_name='Description du poste'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='lieu',
            field=models.CharField(max_length=100, verbose_name='Localisation'),
        ),
        migrations.AlterField(
            model_name='offre',
            name='poste',
            field=models.CharField(max_length=150, verbose_name='Titre du poste'),
        ),
        migrations.DeleteModel(
            name='Evaluation',
        ),
    ]
