# Generated by Django 5.0.14 on 2026-09-24 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_candidature_competences_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidature',
            name='document_fourni',
            field=models.FileField(blank=True, upload_to='candidatures/', verbose_name='Autre document fourni'),
        ),
        migrations.AddField(
            model_name='candidature',
            name='prenom',
            field=models.CharField(blank=True, max_length=100, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='candidature',
            name='nom_candidat',
            field=models.CharField(max_length=150, verbose_name='Nom'),
        ),
    ]
