# Generated by Django 5.0.14 on 2026-09-17 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PredictionAttrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prediction', models.DateTimeField(auto_now_add=True)),
                ('prediction_depart', models.BooleanField()),
                ('probabilite_depart', models.FloatField()),
                ('niveau_risque', models.CharField(max_length=10)),
                ('donnees_utilisees', models.JSONField(help_text='Copie des 29 variables soumises au modele, pour tracabilite/audit.')),
                ('demande_par', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions_demandees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(blank=True, help_text='Vide si la simulation a ete faite sur un profil libre (non lie a une fiche employe).', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='predictions_attrition', to='employees.employe')),
            ],
            options={
                'verbose_name': "Prediction d'attrition",
                'verbose_name_plural': "Predictions d'attrition",
                'ordering': ['-date_prediction'],
            },
        ),
    ]
