# Generated by Django 5.0.14 on 2026-09-17 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EchangeAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('reponse', models.TextField(blank=True)),
                ('en_erreur', models.BooleanField(default=False)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('utilisateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='echanges_assistant', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "Echange avec l'assistant",
                'verbose_name_plural': "Echanges avec l'assistant",
                'ordering': ['-date_creation'],
            },
        ),
    ]
