# Generated by Django 5.0.14 on 2026-09-21 08:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DroitUtilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=30)),
                ('lecture', models.BooleanField(default=False)),
                ('creation', models.BooleanField(default=False)),
                ('modification', models.BooleanField(default=False)),
                ('suppression', models.BooleanField(default=False)),
                ('date_maj', models.DateTimeField(auto_now=True)),
                ('utilisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='droits_personnalises', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Droit personnalise',
                'verbose_name_plural': 'Droits personnalises',
                'unique_together': {('utilisateur', 'module')},
            },
        ),
    ]
