# Generated by Django 5.0.14 on 2026-09-17 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlerteSysteme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=255)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('resolue', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Alerte systeme',
                'verbose_name_plural': 'Alertes systeme',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('justificatif', models.FileField(blank=True, null=True, upload_to='justificatifs_absence/')),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente de validation (RH)'), ('APPROUVEE', 'Approuvee'), ('REJETEE', 'Rejetee')], default='EN_ATTENTE', max_length=10)),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('commentaire_rh', models.CharField(blank=True, max_length=255)),
                ('date_traitement', models.DateTimeField(blank=True, null=True)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='absences', to='employees.employe')),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='absences_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Absence',
                'verbose_name_plural': 'Absences',
                'ordering': ['-date_declaration'],
            },
        ),
        migrations.CreateModel(
            name='DemandeConge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_demande', models.CharField(choices=[('CONGE', 'Conge'), ('PERMISSION', 'Permission')], max_length=12)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('motif', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('EN_ATTENTE_RH', 'En attente de traitement (RH)'), ('EN_ATTENTE_ADMIN', "Transmise a l'Administrateur"), ('APPROUVEE_A_NOTIFIER', 'Approuvee - en attente de notification (RH)'), ('APPROUVEE', 'Approuvee'), ('REJETEE_RH', 'Rejetee par le Responsable RH'), ('REJETEE_ADMIN', "Rejetee par l'Administrateur")], default='EN_ATTENTE_RH', max_length=25)),
                ('date_soumission', models.DateTimeField(auto_now_add=True)),
                ('date_limite_rh', models.DateTimeField(blank=True, null=True)),
                ('commentaire_rh', models.CharField(blank=True, max_length=255)),
                ('date_traitement_rh', models.DateTimeField(blank=True, null=True)),
                ('date_limite_admin', models.DateTimeField(blank=True, null=True)),
                ('commentaire_admin', models.CharField(blank=True, max_length=255)),
                ('date_decision_admin', models.DateTimeField(blank=True, null=True)),
                ('date_limite_notification', models.DateTimeField(blank=True, null=True)),
                ('date_cloture', models.DateTimeField(blank=True, null=True)),
                ('nombre_reaffectations', models.PositiveSmallIntegerField(default=0)),
                ('admin_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conge_a_decider', to=settings.AUTH_USER_MODEL)),
                ('admin_traitant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conge_decidees', to=settings.AUTH_USER_MODEL)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demandes_conge', to='employees.employe')),
                ('rh_assigne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demandes_conge_assignees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demande de conge/permission',
                'verbose_name_plural': 'Demandes de conges/permissions',
                'ordering': ['-date_soumission'],
            },
        ),
        migrations.CreateModel(
            name='Demission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_declaration', models.DateTimeField(auto_now_add=True)),
                ('date_effective_souhaitee', models.DateField()),
                ('motif', models.CharField(blank=True, max_length=255)),
                ('statut', models.CharField(choices=[('DECLAREE', 'Declaree - en attente de transmission (RH)'), ('TRANSMISE_ADMIN', "Transmise a l'Administrateur"), ('PREAVIS_DEFINI', 'Preavis defini - a communiquer (RH)'), ('COMMUNIQUEE', "Decision communiquee a l'employe")], default='DECLAREE', max_length=20)),
                ('date_transmission', models.DateTimeField(blank=True, null=True)),
                ('preavis_jours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('commentaire_admin', models.CharField(blank=True, max_length=255)),
                ('date_decision_admin', models.DateTimeField(blank=True, null=True)),
                ('date_communication', models.DateTimeField(blank=True, null=True)),
                ('employe', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demission', to='employees.employe')),
                ('rh_transmetteur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demissions_transmises', to=settings.AUTH_USER_MODEL)),
                ('traite_par', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demissions_traitees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Demission',
                'verbose_name_plural': 'Demissions',
            },
        ),
    ]
