# Generated by Django 5.0.14 on 2026-09-21 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='type_absence',
            field=models.CharField(choices=[('MALADIE', 'Maladie'), ('DECES', "Deces d'un proche"), ('PERSONNEL', 'Motif personnel'), ('AUTRE', 'Autre')], default='AUTRE', max_length=10, verbose_name="Motif de l'absence"),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='alerte_notification_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='alerte_rh_envoyee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='commentaire',
            field=models.CharField(blank=True, max_length=500, verbose_name='Commentaire complementaire'),
        ),
        migrations.AddField(
            model_name='demandeconge',
            name='piece_jointe',
            field=models.FileField(blank=True, null=True, upload_to='demandes_pj/', verbose_name='Piece jointe'),
        ),
        migrations.AlterField(
            model_name='absence',
            name='motif',
            field=models.CharField(blank=True, max_length=255, verbose_name='Commentaire'),
        ),
    ]
