# Generated by Django 5.0.14 on 2026-09-26 15:43

from django.db import migrations, models


def convertir_en_declarations(apps, schema_editor):
    Absence = apps.get_model("demandes", "Absence")
    Absence.objects.exclude(statut="DECLAREE").update(statut="DECLAREE")


class Migration(migrations.Migration):

    dependencies = [
        ('demandes', '0002_alertes_pj_type_absence'),
    ]

    operations = [
        migrations.RunPython(convertir_en_declarations, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='absence',
            name='statut',
            field=models.CharField(choices=[('DECLAREE', 'Déclarée')], default='DECLAREE', max_length=10),
        ),
    ]
