# Generated by Django 5.0.14 on 2026-09-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activitylog',
            name='adresse_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='navigateur',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='resultat',
            field=models.CharField(choices=[('SUCCES', 'Succès'), ('ALERTE', 'Alerte')], default='SUCCES', max_length=10),
        ),
        migrations.AddField(
            model_name='activitylog',
            name='type_action',
            field=models.CharField(choices=[('CONNEXION', 'Connexion'), ('UTILISATEUR', 'Utilisateurs & droits'), ('EMPLOYE', 'Employés'), ('DEMANDE', 'Demandes'), ('ABSENCE', 'Absences'), ('DEMISSION', 'Démissions'), ('RECRUTEMENT', 'Recrutement'), ('FORMATION', 'Formations'), ('NOTIFICATION', 'Notifications'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='categorie',
            field=models.CharField(choices=[('DEMANDE', 'Demande'), ('ABSENCE', 'Absence'), ('RECRUTEMENT', 'Recrutement'), ('FORMATION', 'Formation'), ('DOCUMENT', 'Document'), ('COMMUNICATION', 'Communication'), ('SECURITE', 'Sécurité'), ('SYSTEME', 'Système'), ('AUTRE', 'Autre')], default='AUTRE', max_length=15),
        ),
        migrations.AddField(
            model_name='notification',
            name='titre',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
